/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: true
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: false  # Disabilita la visualizzazione
    planner_frequency: 1.0  # Aumenta la frequenza del planner
    progress_timeout: 10.0  # Riduci il timeout di progresso
    potential_scale: 1.5  # Riduci la scala dei costi di potenziale
    min_frontier_size: 0.50  # Riduci la dimensione minima della frontiera
    orientation_scale: 0.5  # Aggiungi una leggera importanza all'orientamento
    transform_tolerance: 0.1  # Riduci la tolleranza di trasformazione

