/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: true
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: true  # Mantiene la visualizzazione per debug

    ## 🔥 Ottimizzazione del Planner
    planner_frequency: 1.5  # Aumenta la frequenza di aggiornamento della pianificazione
    progress_timeout: 15.0  # Timeout più basso per evitare blocchi
    potential_scale: 5.0  # Migliora la scelta delle frontiere
    orientation_scale: 0.5  # Evita rotazioni inutili
    gain_scale: 2.0  # Migliora la scelta delle frontiere più vantaggiose
    transform_tolerance: 0.5  # Più tolleranza negli aggiornamenti della trasformata
    min_frontier_size: 0.5  # Esplora anche frontiere più piccole

    ## 🚀 Velocizza l'Esplorazione
    frontier_search_interval: 2.0  # Intervallo più breve tra le ricerche di nuove frontiere
    frontier_clear_distance: 0.3  # Evita di considerare frontiere troppo vicine
    path_distance_bias: 50.0  # Favorisce percorsi più brevi
    goal_distance_bias: 40.0  # Riduce il numero di obiettivi non necessari
    stop_distance: 0.1  # Evita fermate troppo anticipate

    ## 🛠️ Evitare Blocchi
    planner_patience: 5.0  # Tempo massimo prima di rigenerare un piano
    controller_patience: 3.0  # Tempo massimo prima di tentare un nuovo obiettivo
    recovery_behavior_enabled: true  # Abilita comportamenti di recupero (rotazioni, passi indietro)
    oscillation_timeout: 10.0  # Tempo prima di attivare il recupero da oscillazioni
    oscillation_distance: 0.2  # Distanza minima per considerare un'oscillazione

