controller_list:
  - name: arm_controller
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
    trajectory:
      type: JointTrajectory
    goal_time: 0.5
    stop_time: 0.2
    max_velocity_scaling_factor: 0.5
    max_acceleration_scaling_factor: 0.5
    gains:
      arm_1_joint:
        p: 100.0
        d: 0.0
        i: 0.0
      arm_2_joint:
        p: 100.0
        d: 0.0
        i: 0.0
      # Aggiungi le giunture e i guadagni necessari per il resto del braccio
      arm_3_joint:
        p: 100.0
        d: 0.0
        i: 0.0
      arm_4_joint:
        p: 100.0
        d: 0.0
        i: 0.0
      arm_5_joint:
        p: 100.0
        d: 0.0
        i: 0.0
      arm_6_joint:
        p: 100.0
        d: 0.0
        i: 0.0
      arm_7_joint:
        p: 100.0
        d: 0.0
        i: 0.0

