arm_velocitiy_controller:
  ros__parameters:
    
    type: velocity_controllers/JointGroupVelocityController
    
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
      
    #pid_gains:
      #arm_1_joint: {p: 100.0, i: 10.0, d: 0.1} # change these
      #arm_2_joint: {p: 100.0, i: 10.0, d: 0.1}
      #arm_3_joint: {p: 100.0, i: 100.0, d: 1.0}
      #arm_4_joint: {p: 100.0, i: 10.0, d: 0.1}
      #arm_5_joint: {p: 100.0, i: 10.0, d: 0.1}
      #arm_6_joint: {p: 100.0, i: 100.0, d: 1.0}
      #arm_7_joint: {p: 100.0, i: 10.0, d: 0.1}
        
    interface_name: velocity
    command_interfaces:
     - velocity
    state_interfaces:
      - position
      - velocity
    #interface_name: velocity
    
    
arm_impedance_controller:
  ros__parameters:
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
    command_joints:
      - gravity_compensation_controller/arm_1_joint
      - gravity_compensation_controller/arm_2_joint
      - gravity_compensation_controller/arm_3_joint
      - gravity_compensation_controller/arm_4_joint
      - gravity_compensation_controller/arm_5_joint
      - gravity_compensation_controller/arm_6_joint
      - gravity_compensation_controller/arm_7_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      arm_1_joint:
        goal: 0.02
      arm_2_joint:
        goal: 0.02
      arm_3_joint:
        goal: 0.02
      arm_4_joint:
        goal: 0.02
      arm_5_joint:
        goal: 0.02
      arm_6_joint:
        goal: 0.02
      arm_7_joint:
        goal: 0.02 
