arm_position_controller:
  ros__parameters:    
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
      
    #pid_gains:
      #arm_1_joint: {p: 1.0, i: 0.1, d: 0.1} # change these
      #arm_2_joint: {p: 100.0, i: 10.0, d: 0.1}
      #arm_3_joint: {p: 100.0, i: 100.0, d: 1.0}
      #arm_4_joint: {p: 100.0, i: 10.0, d: 0.1}
      #arm_5_joint: {p: 100.0, i: 10.0, d: 0.1}
      #arm_6_joint: {p: 100.0, i: 100.0, d: 1.0}
      #arm_7_joint: {p: 100.0, i: 10.0, d: 0.1}
      
      
